# Generated by Django 3.2.6 on 2021-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDs', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
