# Generated by Django 3.2.6 on 2021-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedInfo',
            fields=[
                ('feedID', models.IntegerField(primary_key=True, serialize=False)),
                ('species', models.IntegerField()),
                ('brand', models.CharField(default='no brand info', max_length=20)),
                ('feedName', models.CharField(default='no feedName info', max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDs', models.IntegerField()),
                ('name', models.CharField(default='guest', max_length=20)),
                ('pw', models.CharField(default='abcdefgh', max_length=20)),
            ],
        ),
    ]
