# Generated by Django 3.2.6 on 2021-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='foodShape',
            field=models.CharField(default='no info', max_length=10),
        ),
    ]
