# Generated by Django 3.2.6 on 2021-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pw',
            field=models.CharField(default='abcdefgh', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
