# Generated by Django 3.2.6 on 2021-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210902_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedInfo',
            fields=[
                ('feedID', models.IntegerField(primary_key=True, serialize=False)),
                ('species', models.IntegerField()),
                ('brand', models.CharField(default='no brand info', max_length=20)),
                ('feedName', models.CharField(default='no feedName info', max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
