# Generated by Django 3.2.6 on 2021-09-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_feedinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='IDs',
        ),
    ]
