# Generated by Django 3.2.6 on 2021-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_userinfo_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinfo',
            name='feedID',
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
