# Generated by Django 3.2.6 on 2021-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_feedinfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinfo',
            name='feedName',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='species',
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='alg',
            field=models.CharField(default='no allergy data', max_length=40),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='explain',
            field=models.CharField(default='no explain data', max_length=1000),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='flavor',
            field=models.CharField(default='no Flavor data', max_length=40),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='foodType',
            field=models.CharField(default='no info', max_length=10),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='health',
            field=models.CharField(default='no health data', max_length=20),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='name',
            field=models.CharField(default='no feedName data', max_length=40),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='size',
            field=models.CharField(default='no size data', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='brand',
            field=models.CharField(default='no brand data', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
